services:
    apache:
        image: php:apache
        container_name: php-test
        ports:
            - '8282:80'
        volumes:
            - ./website:/var/www/html
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: n&3@3-4DN_.e
            MYSQL_DATABASE: backenddocker
        ports:
            - "3308:3308"
        volumes:
            - db_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8686:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: n&3@3-4DN_.e
            UPLOAD_LIMIT: 10G

volumes:
    db_data:
